### ISSUE TITLE
Logo Design: TRPGMaker

### ISSUE THREAD

**Issue by baranpirincal** [Narratech/TRPGMaker#10]
Hello!

 I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by federicopeinado** [comment]
Oh, great! Go for it!
We would love to see what you coukd make :)

**Comment by baranpirincal** [comment]
@federicopeinado 

Hey again,

Do you have an any idea about design? :)

**Comment by federicopeinado** [comment]
Umm, an obvious reference is the logo of the famous RPG Maker:
https://www.google.es/search?rls=com.microsoft%3Aes&biw=1920&bih=947&tbm=isch&sa=1&ei=Kl87W6GeGcvyUL2BlagJ&q=rpgmaker+logo&oq=rpgmaker+logo&gs_l=img.3..0i8i30k1.58407.60167.0.60359.6.6.0.0.0.0.92.344.6.6.0....0...1c.1.64.img..0.6.343...0j0i10k1j0i7i30k1j0i30k1j0i10i30k1j0i10i24k1.0.eFi2y0V0x18

But I think we can use a more "serious" typography (like that used in Unity or Unreal Engine logos)... or maybe we should play a little bit with the idea of "isometry" (maybe the letter T is like a sword or something like that on top of a "board" with three isometric tiles: the letters R, P and G). 

What do you think? :-)

**Comment by baranpirincal** [comment]
Hey @federicopeinado ,

Sorry for the delay. I was too busy last week.

I finished (sword) T letter. Maybe we can use this for an application icon. Now I will combine it with "RPGMaker". But I did not understand your isometric tiles idea. Can you explain a bit or if you have an any idea,suggestion or comments please share with me! :)

Best Regards
Baran Pirinçal

![trrpgmaker](https://user-images.githubusercontent.com/37786733/42630852-0334e852-85e1-11e8-9488-b3b6f54bbb16.jpg)

**Comment by federicopeinado** [comment]
Great! It is lovely for an icon... maybe the yellow&black lines in the sword look a little bit strange (like a warning signal).

I add an sketch about muy ideas for the isometric tiles :-)
![trpg maker logo idea](https://user-images.githubusercontent.com/5931002/42650557-fddc1282-860c-11e8-875d-25dc60c5081f.png)

**Comment by baranpirincal** [comment]
Hey @federicopeinado 

I combined isometric tiles according to your idea.

We can change colors as you wish.

I am waiting your comments! :)

![trpgmaker](https://user-images.githubusercontent.com/37786733/42660538-29526f5c-8634-11e8-8ea6-2e18c4469c57.jpg)

**Comment by federicopeinado** [comment]
Great! I love the third example :-)

I have some suggestions for improvement (making an isometric sword, combining the same three colors (or similar ones):
![win_20180713_00_11_43_pro 2](https://user-images.githubusercontent.com/5931002/42662434-e1b668ee-8631-11e8-93a4-0fb4bdfd1503.jpg)

**Comment by federicopeinado** [comment]
As you see the sword is more clearly a T. With a sphere with a green jewel or so at the end... but the basic form is an isometric T.

**Comment by baranpirincal** [comment]
I did not touch the colors yet. We will change it but firstly we need to be sure about form of sword.

Also, I will add jewel on top of the "T".

How about the thickness and angle of "T" and which one do you prefer?

I am waiting your comment! :)



![untitled-1](https://user-images.githubusercontent.com/37786733/42690112-cc8a2670-86ab-11e8-9896-2ded6177d6fe.jpg)

**Comment by federicopeinado** [comment]
Lovely! I like the last one (the thin one). The idea of the jewel (sphere or something) is to show clearly that it should be seen as a T letter, not a cross ;-)

Note also the orientation of the RPG letters... in my draft they have all the same :-D (everything is for the reader to identify the "TRPG" acronym, hehe)

**Comment by federicopeinado** [comment]
Instead of having a dark (almost black) shadow, the other sides of the sword could be lighter :-)

**Comment by baranpirincal** [comment]
Hey @federicopeinado 

- I made directions of letters same
- removed cross lines on sword
- same thickness ( letters and sword )
- lighter shadow
- added diamond

However, we should choose color palette for Sword. What do you prefer? I am waiting your opinion.


![untitled-1](https://user-images.githubusercontent.com/37786733/42976758-1a5e6c92-8bcc-11e8-8977-a47653131f9c.jpg)

Best Regards
Baran Pirinçal
